import forms from "@tailwindcss/forms";
import typography from "@tailwindcss/typography";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
// Design tokens mirror the approved Citely mockups (Material-3-derived palette,
// Source Serif 4 for scholarly body/headings, Inter for UI labels/citations).
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        outline: "#74777d",
        "on-surface-variant": "#44474d",
        "inverse-primary": "#b6c8e4",
        "surface-bright": "#faf9f8",
        "tertiary-container": "#3b2707",
        "outline-variant": "#c4c6cd",
        "on-primary": "#ffffff",
        "primary-fixed": "#d3e4ff",
        "on-secondary-container": "#761f27",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffddb2",
        "on-primary-container": "#8294ae",
        "on-tertiary-fixed": "#291800",
        secondary: "#9f3e43",
        "on-error": "#ffffff",
        surface: "#faf9f8",
        "inverse-surface": "#2f3130",
        "surface-container": "#eeeeed",
        "on-secondary-fixed": "#400009",
        tertiary: "#221300",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#1a2c42",
        background: "#faf9f8",
        "surface-container-high": "#e9e8e7",
        "surface-tint": "#4e6078",
        "surface-variant": "#e3e2e1",
        "secondary-container": "#ff888b",
        "on-secondary-fixed-variant": "#80272e",
        "secondary-fixed-dim": "#ffb3b3",
        "inverse-on-surface": "#f1f0f0",
        primary: "#04172c",
        "primary-fixed-dim": "#b6c8e4",
        error: "#ba1a1a",
        "on-surface": "#1a1c1c",
        "on-tertiary-fixed-variant": "#5a4320",
        "on-primary-fixed": "#091c32",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f4f3f2",
        "tertiary-fixed-dim": "#e3c195",
        "on-primary-fixed-variant": "#36485f",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#ffdad9",
        "surface-container-highest": "#e3e2e1",
        "on-tertiary-container": "#ac8d64",
        "on-background": "#1a1c1c",
        "surface-dim": "#dadad9",
        // semantic accents used by verification / status chips
        "verify-bg": "#e6f4ea",
        "verify-fg": "#1e8e3e",
        "warn-bg": "#fff8e6",
        "warn-fg": "#b07b00",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        gutter: "24px",
      },
      maxWidth: {
        "container-max": "1280px",
        "article-width": "720px",
      },
      fontFamily: {
        "headline-lg": ["Source Serif 4", "serif"],
        "ui-label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Source Serif 4", "serif"],
        "display-lg": ["Source Serif 4", "serif"],
        "ui-label-md": ["Inter", "sans-serif"],
        "citation-caps": ["Inter", "sans-serif"],
        "article-body": ["Source Serif 4", "serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "ui-label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "ui-label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "citation-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "article-body": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      keyframes: {
        fadeInUp: {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in-up": "fadeInUp 0.4s ease-out forwards",
      },
    },
  },
  plugins: [forms, typography, containerQueries],
};
